include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-watchdog
PKG_VERSION:=1.0.0
PKG_RELEASE:=20260816

PKG_MAINTAINER:=iamxiaojianzheng  <xjz.jiahe@gmail.com>
PKG_CONFIG_DEPENDS:=

LUCI_TITLE:=LuCI support for watchdog
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+watchdog

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
